steps:
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
      - 'stale'
    owner: 'SAP'
    repository: 'jenkins-library'
    releaseBodyHeader: ''
  githubCreatePullRequest:
    base: master
    owner: 'SAP'
    repository: 'jenkins-library'
    labels:
      - 'REVIEW'
      - 'go-piper'
    assignees:
      - 'marcusholl'
      - 'daniel-kurzynski'
      - 'fwilhe'
      - 'CCFenner'
      - 'OliverNocon'
      - 'nevskrem'
general:
  cfApiEndpoint: 'http://prs74965.nonprod.portsmouth.jlrint.com:8000/sap/bc/adt'
  cfOrg: 'your-cf-org'
  cfSpace: 'yourSpace'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'abapEnvironmentPipeline'
  cfServiceKeyName: 'jenkins_sap_com_0510'
stages:
  Prepare System:
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemAdminEmail: 'user@example.com'
    abapSystemDescription: 'ABAP Environment Sandbox System'
    abapSystemIsDevelopmentAllowed: false
    abapSystemID: 'TES'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1
    cfServiceKeyConfig: 'sap_com_0510.json'
  Clone Repositories:
    strategy: 'Clone'
    repositories: 'repositories.yml'
  ATC:
    atcConfig: 'atcConfig.yml'
steps:
  cloudFoundryDeleteService:
    cfDeleteServiceKeys: true
